<?php

namespace App\View\Components\Widgets;

use App\Models\Account;
use App\Models\Transaction;
use Illuminate\View\Component;
use stdClass;

class TransactionList extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public $counrty = [
        ['name' => 'Afghanistan', 'code' => 'AF'], 
        ['name' => 'Åland Islands', 'code' => 'AX'], 
        ['name' => 'Albania', 'code' => 'AL'], 
        ['name' => 'Algeria', 'code' => 'DZ'], 
        ['name' => 'American Samoa', 'code' => 'AS'], 
        ['name' => 'AndorrA', 'code' => 'AD'], 
        ['name' => 'Angola', 'code' => 'AO'], 
        ['name' => 'Anguilla', 'code' => 'AI'], 
        ['name' => 'Antarctica', 'code' => 'AQ'], 
        ['name' => 'Antigua and Barbuda', 'code' => 'AG'], 
        ['name' => 'Argentina', 'code' => 'AR'], 
        ['name' => 'Armenia', 'code' => 'AM'], 
        ['name' => 'Aruba', 'code' => 'AW'], 
        ['name' => 'Australia', 'code' => 'AU'], 
        ['name' => 'Austria', 'code' => 'AT'], 
        ['name' => 'Azerbaijan', 'code' => 'AZ'], 
        ['name' => 'Bahamas', 'code' => 'BS'], 
        ['name' => 'Bahrain', 'code' => 'BH'], 
        ['name' => 'Bangladesh', 'code' => 'BD'], 
        ['name' => 'Barbados', 'code' => 'BB'], 
        ['name' => 'Belarus', 'code' => 'BY'], 
        ['name' => 'Belgium', 'code' => 'BE'], 
        ['name' => 'Belize', 'code' => 'BZ'], 
        ['name' => 'Benin', 'code' => 'BJ'], 
        ['name' => 'Bermuda', 'code' => 'BM'], 
        ['name' => 'Bhutan', 'code' => 'BT'], 
        ['name' => 'Bolivia', 'code' => 'BO'], 
        ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'], 
        ['name' => 'Botswana', 'code' => 'BW'], 
        ['name' => 'Bouvet Island', 'code' => 'BV'], 
        ['name' => 'Brazil', 'code' => 'BR'], 
        ['name' => 'British Indian Ocean Territory', 'code' => 'IO'], 
        ['name' => 'Brunei Darussalam', 'code' => 'BN'], 
        ['name' => 'Bulgaria', 'code' => 'BG'], 
        ['name' => 'Burkina Faso', 'code' => 'BF'], 
        ['name' => 'Burundi', 'code' => 'BI'], 
        ['name' => 'Cambodia', 'code' => 'KH'], 
        ['name' => 'Cameroon', 'code' => 'CM'], 
        ['name' => 'Canada', 'code' => 'CA'], 
        ['name' => 'Cape Verde', 'code' => 'CV'], 
        ['name' => 'Cayman Islands', 'code' => 'KY'], 
        ['name' => 'Central African Republic', 'code' => 'CF'], 
        ['name' => 'Chad', 'code' => 'TD'], 
        ['name' => 'Chile', 'code' => 'CL'], 
        ['name' => 'China', 'code' => 'CN'], 
        ['name' => 'Christmas Island', 'code' => 'CX'], 
        ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'], 
        ['name' => 'Colombia', 'code' => 'CO'], 
        ['name' => 'Comoros', 'code' => 'KM'], 
        ['name' => 'Congo', 'code' => 'CG'], 
        ['name' => 'Congo, The Democratic Republic of the', 'code' => 'CD'], 
        ['name' => 'Cook Islands', 'code' => 'CK'], 
        ['name' => 'Costa Rica', 'code' => 'CR'], 
        ['name' => 'Cote D\'Ivoire', 'code' => 'CI'], 
        ['name' => 'Croatia', 'code' => 'HR'], 
        ['name' => 'Cuba', 'code' => 'CU'], 
        ['name' => 'Cyprus', 'code' => 'CY'], 
        ['name' => 'Czech Republic', 'code' => 'CZ'], 
        ['name' => 'Denmark', 'code' => 'DK'], 
        ['name' => 'Djibouti', 'code' => 'DJ'], 
        ['name' => 'Dominica', 'code' => 'DM'], 
        ['name' => 'Dominican Republic', 'code' => 'DO'], 
        ['name' => 'Ecuador', 'code' => 'EC'], 
        ['name' => 'Egypt', 'code' => 'EG'], 
        ['name' => 'El Salvador', 'code' => 'SV'], 
        ['name' => 'Equatorial Guinea', 'code' => 'GQ'], 
        ['name' => 'Eritrea', 'code' => 'ER'], 
        ['name' => 'Estonia', 'code' => 'EE'], 
        ['name' => 'Ethiopia', 'code' => 'ET'], 
        ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'], 
        ['name' => 'Faroe Islands', 'code' => 'FO'], 
        ['name' => 'Fiji', 'code' => 'FJ'], 
        ['name' => 'Finland', 'code' => 'FI'], 
        ['name' => 'France', 'code' => 'FR'], 
        ['name' => 'French Guiana', 'code' => 'GF'], 
        ['name' => 'French Polynesia', 'code' => 'PF'], 
        ['name' => 'French Southern Territories', 'code' => 'TF'], 
        ['name' => 'Gabon', 'code' => 'GA'], 
        ['name' => 'Gambia', 'code' => 'GM'], 
        ['name' => 'Georgia', 'code' => 'GE'], 
        ['name' => 'Germany', 'code' => 'DE'], 
        ['name' => 'Ghana', 'code' => 'GH'], 
        ['name' => 'Gibraltar', 'code' => 'GI'], 
        ['name' => 'Greece', 'code' => 'GR'], 
        ['name' => 'Greenland', 'code' => 'GL'], 
        ['name' => 'Grenada', 'code' => 'GD'], 
        ['name' => 'Guadeloupe', 'code' => 'GP'], 
        ['name' => 'Guam', 'code' => 'GU'], 
        ['name' => 'Guatemala', 'code' => 'GT'], 
        ['name' => 'Guernsey', 'code' => 'GG'], 
        ['name' => 'Guinea', 'code' => 'GN'], 
        ['name' => 'Guinea-Bissau', 'code' => 'GW'], 
        ['name' => 'Guyana', 'code' => 'GY'], 
        ['name' => 'Haiti', 'code' => 'HT'], 
        ['name' => 'Heard Island and Mcdonald Islands', 'code' => 'HM'], 
        ['name' => 'Holy See (Vatican City State)', 'code' => 'VA'], 
        ['name' => 'Honduras', 'code' => 'HN'], 
        ['name' => 'Hong Kong', 'code' => 'HK'], 
        ['name' => 'Hungary', 'code' => 'HU'], 
        ['name' => 'Iceland', 'code' => 'IS'], 
        ['name' => 'India', 'code' => 'IN'], 
        ['name' => 'Indonesia', 'code' => 'ID'], 
        ['name' => 'Iran, Islamic Republic Of', 'code' => 'IR'], 
        ['name' => 'Iraq', 'code' => 'IQ'], 
        ['name' => 'Ireland', 'code' => 'IE'], 
        ['name' => 'Isle of Man', 'code' => 'IM'], 
        ['name' => 'Israel', 'code' => 'IL'], 
        ['name' => 'Italy', 'code' => 'IT'], 
        ['name' => 'Jamaica', 'code' => 'JM'], 
        ['name' => 'Japan', 'code' => 'JP'], 
        ['name' => 'Jersey', 'code' => 'JE'], 
        ['name' => 'Jordan', 'code' => 'JO'], 
        ['name' => 'Kazakhstan', 'code' => 'KZ'], 
        ['name' => 'Kenya', 'code' => 'KE'], 
        ['name' => 'Kiribati', 'code' => 'KI'], 
        ['name' => 'Korea, Democratic People\'S Republic of', 'code' => 'KP'], 
        ['name' => 'Korea, Republic of', 'code' => 'KR'], 
        ['name' => 'Kuwait', 'code' => 'KW'], 
        ['name' => 'Kyrgyzstan', 'code' => 'KG'], 
        ['name' => 'Lao People\'S Democratic Republic', 'code' => 'LA'], 
        ['name' => 'Latvia', 'code' => 'LV'], 
        ['name' => 'Lebanon', 'code' => 'LB'], 
        ['name' => 'Lesotho', 'code' => 'LS'], 
        ['name' => 'Liberia', 'code' => 'LR'], 
        ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LY'], 
        ['name' => 'Liechtenstein', 'code' => 'LI'], 
        ['name' => 'Lithuania', 'code' => 'LT'], 
        ['name' => 'Luxembourg', 'code' => 'LU'], 
        ['name' => 'Macao', 'code' => 'MO'], 
        ['name' => 'Macedonia, The Former Yugoslav Republic of', 'code' => 'MK'], 
        ['name' => 'Madagascar', 'code' => 'MG'], 
        ['name' => 'Malawi', 'code' => 'MW'], 
        ['name' => 'Malaysia', 'code' => 'MY'], 
        ['name' => 'Maldives', 'code' => 'MV'], 
        ['name' => 'Mali', 'code' => 'ML'], 
        ['name' => 'Malta', 'code' => 'MT'], 
        ['name' => 'Marshall Islands', 'code' => 'MH'], 
        ['name' => 'Martinique', 'code' => 'MQ'], 
        ['name' => 'Mauritania', 'code' => 'MR'], 
        ['name' => 'Mauritius', 'code' => 'MU'], 
        ['name' => 'Mayotte', 'code' => 'YT'], 
        ['name' => 'Mexico', 'code' => 'MX'], 
        ['name' => 'Micronesia, Federated States of', 'code' => 'FM'], 
        ['name' => 'Moldova, Republic of', 'code' => 'MD'], 
        ['name' => 'Monaco', 'code' => 'MC'], 
        ['name' => 'Mongolia', 'code' => 'MN'], 
        ['name' => 'Montserrat', 'code' => 'MS'], 
        ['name' => 'Morocco', 'code' => 'MA'], 
        ['name' => 'Mozambique', 'code' => 'MZ'], 
        ['name' => 'Myanmar', 'code' => 'MM'], 
        ['name' => 'Namibia', 'code' => 'NA'], 
        ['name' => 'Nauru', 'code' => 'NR'], 
        ['name' => 'Nepal', 'code' => 'NP'], 
        ['name' => 'Netherlands', 'code' => 'NL'], 
        ['name' => 'Netherlands Antilles', 'code' => 'AN'], 
        ['name' => 'New Caledonia', 'code' => 'NC'], 
        ['name' => 'New Zealand', 'code' => 'NZ'], 
        ['name' => 'Nicaragua', 'code' => 'NI'], 
        ['name' => 'Niger', 'code' => 'NE'], 
        ['name' => 'Nigeria', 'code' => 'NG'], 
        ['name' => 'Niue', 'code' => 'NU'], 
        ['name' => 'Norfolk Island', 'code' => 'NF'], 
        ['name' => 'Northern Mariana Islands', 'code' => 'MP'], 
        ['name' => 'Norway', 'code' => 'NO'], 
        ['name' => 'Oman', 'code' => 'OM'], 
        ['name' => 'Pakistan', 'code' => 'PK'], 
        ['name' => 'Palau', 'code' => 'PW'], 
        ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS'], 
        ['name' => 'Panama', 'code' => 'PA'], 
        ['name' => 'Papua New Guinea', 'code' => 'PG'], 
        ['name' => 'Paraguay', 'code' => 'PY'], 
        ['name' => 'Peru', 'code' => 'PE'], 
        ['name' => 'Philippines', 'code' => 'PH'], 
        ['name' => 'Pitcairn', 'code' => 'PN'], 
        ['name' => 'Poland', 'code' => 'PL'], 
        ['name' => 'Portugal', 'code' => 'PT'], 
        ['name' => 'Puerto Rico', 'code' => 'PR'], 
        ['name' => 'Qatar', 'code' => 'QA'], 
        ['name' => 'Reunion', 'code' => 'RE'], 
        ['name' => 'Romania', 'code' => 'RO'], 
        ['name' => 'Russian Federation', 'code' => 'RU'], 
        ['name' => 'RWANDA', 'code' => 'RW'], 
        ['name' => 'Saint Helena', 'code' => 'SH'], 
        ['name' => 'Saint Kitts and Nevis', 'code' => 'KN'], 
        ['name' => 'Saint Lucia', 'code' => 'LC'], 
        ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'], 
        ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'], 
        ['name' => 'Samoa', 'code' => 'WS'], 
        ['name' => 'San Marino', 'code' => 'SM'], 
        ['name' => 'Sao Tome and Principe', 'code' => 'ST'], 
        ['name' => 'Saudi Arabia', 'code' => 'SA'], 
        ['name' => 'Senegal', 'code' => 'SN'], 
        ['name' => 'Serbia and Montenegro', 'code' => 'CS'], 
        ['name' => 'Seychelles', 'code' => 'SC'], 
        ['name' => 'Sierra Leone', 'code' => 'SL'], 
        ['name' => 'Singapore', 'code' => 'SG'], 
        ['name' => 'Slovakia', 'code' => 'SK'], 
        ['name' => 'Slovenia', 'code' => 'SI'], 
        ['name' => 'Solomon Islands', 'code' => 'SB'], 
        ['name' => 'Somalia', 'code' => 'SO'], 
        ['name' => 'South Africa', 'code' => 'ZA'], 
        ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'], 
        ['name' => 'Spain', 'code' => 'ES'], 
        ['name' => 'Sri Lanka', 'code' => 'LK'], 
        ['name' => 'Sudan', 'code' => 'SD'], 
        ['name' => 'Suriname', 'code' => 'SR'], 
        ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'], 
        ['name' => 'Swaziland', 'code' => 'SZ'], 
        ['name' => 'Sweden', 'code' => 'SE'], 
        ['name' => 'Switzerland', 'code' => 'CH'], 
        ['name' => 'Syrian Arab Republic', 'code' => 'SY'], 
        ['name' => 'Taiwan, Province of China', 'code' => 'TW'], 
        ['name' => 'Tajikistan', 'code' => 'TJ'], 
        ['name' => 'Tanzania, United Republic of', 'code' => 'TZ'], 
        ['name' => 'Thailand', 'code' => 'TH'], 
        ['name' => 'Timor-Leste', 'code' => 'TL'], 
        ['name' => 'Togo', 'code' => 'TG'], 
        ['name' => 'Tokelau', 'code' => 'TK'], 
        ['name' => 'Tonga', 'code' => 'TO'], 
        ['name' => 'Trinidad and Tobago', 'code' => 'TT'], 
        ['name' => 'Tunisia', 'code' => 'TN'], 
        ['name' => 'Turkey', 'code' => 'TR'], 
        ['name' => 'Turkmenistan', 'code' => 'TM'], 
        ['name' => 'Turks and Caicos Islands', 'code' => 'TC'], 
        ['name' => 'Tuvalu', 'code' => 'TV'], 
        ['name' => 'Uganda', 'code' => 'UG'], 
        ['name' => 'Ukraine', 'code' => 'UA'], 
        ['name' => 'United Arab Emirates', 'code' => 'AE'], 
        ['name' => 'United Kingdom', 'code' => 'GB'], 
        ['name' => 'United States', 'code' => 'US'], 
        ['name' => 'United States Minor Outlying Islands', 'code' => 'UM'], 
        ['name' => 'Uruguay', 'code' => 'UY'], 
        ['name' => 'Uzbekistan', 'code' => 'UZ'], 
        ['name' => 'Vanuatu', 'code' => 'VU'], 
        ['name' => 'Venezuela', 'code' => 'VE'], 
        ['name' => 'Viet Nam', 'code' => 'VN'], 
        ['name' => 'Virgin Islands, British', 'code' => 'VG'], 
        ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'], 
        ['name' => 'Wallis and Futuna', 'code' => 'WF'], 
        ['name' => 'Western Sahara', 'code' => 'EH'], 
        ['name' => 'Yemen', 'code' => 'YE'], 
        ['name' => 'Zambia', 'code' => 'ZM'], 
        ['name' => 'Zimbabwe', 'code' => 'ZW'] 
    ];
    
    public $names = [
        "Emily", "Hannah", "Madison", "Ashley", "Sarah", "Alexis", "Samantha", "Jessica", 
        "Elizabeth", "Taylor", "Lauren", "Alyssa", "Kayla", "Abigail", "Brianna", "Olivia", "Emma", 
        "Megan", "Grace", "Victoria", "Rachel", "Anna", "Sydney", "Destiny", "Morgan", "Jennifer", 
        "Jasmine", "Haley", "Julia", "Kaitlyn", "Nicole", "Amanda", "Katherine", "Natalie", "Hailey", 
        "Alexandra", "Savannah", "Chloe", "Rebecca", "Stephanie", "Maria", "Sophia", "Mackenzie", "Allison", 
        "Isabella", "Mary", "Amber", "Danielle", "Gabrielle", "Jordan", "Brooke", "Michelle", "Sierra", 
        "Katelyn", "Andrea", "Madeline", "Sara", "Kimberly", "Courtney", "Erin", "Brittany", "Vanessa", 
        "Jenna", "Jacqueline", "Caroline", "Faith", "Makayla", "Bailey", "Paige", "Shelby", "Melissa", 
        "Kaylee", "Christina", "Trinity", "Mariah", "Caitlin", "Autumn", "Marissa", "Angela", "Breanna", 
        "Catherine", "Zoe", "Briana", "Jada", "Laura", "Claire", "Alexa", "Kelsey", "Kathryn", "Leslie", 
        "Alexandria", "Sabrina", "Mia", "Isabel", "Molly", "Katie", "Leah", "Gabriella", "Cheyenne", 
        "Cassandra", "Tiffany", "Erica", "Lindsey", "Kylie", "Amy", "Diana", "Cassidy", "Mikayla", "Ariana",
        "Margaret", "Kelly", "Miranda", "Maya", "Melanie", "Audrey", "Jade", "Gabriela", "Caitlyn", "Angel", 
        "Jillian", "Alicia", "Jocelyn", "Erika", "Lily", "Heather", "Madelyn", "Adriana", "Arianna", "Lillian", 
        "Kiara", "Riley", "Crystal", "Mckenzie", "Meghan", "Skylar", "Ana", "Britney", "Angelica", "Kennedy", 
        "Chelsea", "Daisy", "Kristen", "Veronica", "Isabelle", "Summer", "Hope", "Brittney", "Lydia", "Hayley", 
        "Evelyn", "Bethany", "Shannon", "Karen", "Michaela", "Jamie", "Daniela", "Angelina", "Kaitlin", "Karina", 
        "Sophie", "Sofia", "Diamond", "Payton", "Cynthia", "Alexia", "Valerie", "Monica", "Peyton", "Carly", "Bianca",
        "Hanna", "Brenda", "Rebekah", "Alejandra", "Mya", "Avery", "Brooklyn", "Ashlyn", "Lindsay", "Ava", "Desiree",
        "Alondra", "Camryn", "Ariel", "Naomi", "Jordyn", "Kendra", "Mckenna", "Holly", "Julie", "Kendall", "Kara",
        "Jasmin", "Selena", "Esmeralda", "Amaya", "Kylee", "Maggie", "Makenzie", "Claudia", "Kyra", "Cameron",
        "Karla", "Kathleen", "Abby", "Delaney", "Amelia", "Casey", "Serena", "Savanna", "Aaliyah", "Giselle",
        "Mallory", "April", "Adrianna", "Raven", "Christine", "Kristina", "Nina", "Asia", "Natalia", "Valeria", 
        "Aubrey", "Lauryn", "Kate", "Patricia", "Jazmin", "Rachael", "Katelynn", "Cierra", "Alison", "Nancy", "Macy", 
        "Elena", "Kyla", "Katrina", "Jazmine", "Joanna", "Tara", "Gianna", "Juliana", "Fatima", "Sadie", "Allyson", 
        "Gracie", "Guadalupe", "Genesis", "Yesenia", "Julianna", "Skyler", "Tatiana", "Alexus", "Alana", "Elise", 
        "Kirsten", "Nadia", "Sandra", "Ruby", "Dominique", "Haylee", "Jayla", "Tori", "Cindy", "Ella", "Sidney", 
        "Tessa", "Carolina", "Jaqueline", "Camille", "Carmen", "Whitney", "Vivian", "Priscilla", "Bridget", "Celeste", 
        "Kiana", "Makenna", "Alissa", "Madeleine", "Miriam", "Natasha", "Ciara", "Cecilia", "Kassandra", "Mercedes", 
        "Reagan", "Aliyah", "Josephine", "Charlotte", "Rylee", "Shania", "Kira", "Meredith", "Eva", "Lisa", "Dakota", 
        "Hallie", "Anne", "Rose", "Liliana", "Kristin", "Deanna", "Imani", "Marisa", "Kailey", "Annie", "Nia", "Carolyn", 
        "Anastasia", "Brenna", "Dana", "Shayla", "Ashlee", "Kassidy", "Alaina", "Wendy", "Rosa", "Logan", "Tabitha", "Paola", 
        "Callie", "Addison", "Lucy", "Gillian", "Clarissa", "Esther", "Destinee", "Josie", "Denise", "Katlyn", "Mariana", 
        "Bryanna", "Emilee", "Georgia", "Kamryn", "Deja", "Ashleigh", "Cristina", "Ruth", "Baylee", "Heaven", "Raquel", 
        "Monique", "Teresa", "Helen", "Krystal", "Tiana", "Cassie", "Kayleigh", "Marina", "Ivy", "Heidi", "Clara", "Ashton", "Meagan", "Gina", "Linda", "Gloria", "Jacquelyn", "Ellie", "Jenny", "Renee", "Daniella", "Lizbeth", "Anahi", "Virginia", "Gisselle", "Kaitlynn", "Julissa", "Cheyanne", "Lacey", "Haleigh", "Marie", "Martha", "Eleanor", "Kierra", "Tiara", "Talia", "Eliza", "Kaylie", "Mikaela", "Harley", "Jaden", "Hailee", "Madalyn", "Kasey", "Ashlynn", "Brandi", "Lesly", "Elisabeth", "Allie", "Viviana", "Cara", "Marisol", "India", "Litzy", "Tatyana", "Melody", "Jessie", "Brandy", "Alisha", "Hunter", "Noelle", "Carla", "Francesca", "Tia", "Layla", "Krista", "Zoey", "Carley", "Janet", "Carissa", "Iris", "Susan", "Kaleigh", "Tyler", "Tamara", "Theresa", "Yasmine", "Tatum", "Sharon", "Alice", "Yasmin", "Tamia", "Abbey", "Alayna", "Kali", "Lilly", "Bailee", "Lesley", "Mckayla", "Ayanna", "Serenity", "Karissa", "Precious", "Jane", "Maddison", "Jayda", "Lexi", "Kelsie", "Phoebe", "Halle", "Kiersten", "Kiera", "Tyra", "Annika", "Felicity", "Taryn", "Kaylin", "Ellen", "Kiley", "Jaclyn", "Rhiannon", "Madisyn", "Colleen", "Joy", "Charity", "Pamela", "Tania", "Fiona", "Kaila", "Irene", "Alyson", "Annabelle", "Emely", "Angelique", "Alina", "Johanna", "Regan", "Janelle", "Janae", "Madyson", "Paris", "Justine", "Chelsey", "Sasha", "Paulina", "Mayra", "Zaria", "Skye", "Cora", "Brisa", "Emilie", "Felicia", "Tianna", "Larissa", "Macie", "Aurora", "Sage", "Lucia", "Alma", "Chasity", "Ann", "Deborah", "Nichole", "Jayden", "Alanna", "Malia", "Carlie", "Angie", "Nora", "Sylvia", "Carrie", "Kailee", "Elaina", "Sonia", "Barbara", "Kenya", "Genevieve", "Piper", "Marilyn", "Amari", "Macey", "Marlene", "Julianne", "Tayler", "Brooklynn", "Lorena", "Perla", "Elisa", "Eden", "Kaley", "Leilani", "Miracle", "Devin", "Aileen", "Chyna", "Esperanza", "Athena", "Regina", "Adrienne", "Shyanne", "Luz", "Tierra", "Clare", "Cristal", "Eliana", "Kelli", "Eve", "Sydnee", "Madelynn", "Breana", "Melina", "Arielle", "Justice", "Toni", "Corinne", "Abbigail", "Maia", "Tess", "Ciera", "Ebony", "Lena", "Maritza", "Lexie", "Isis", "Aimee", "Leticia", "Sydni", "Sarai", "Halie", "Alivia", "Destiney", "Laurel", "Edith", "Fernanda", "Carina", "Amya", "Destini", "Aspen", "Nathalie", "Paula", "Tanya", "Tina", "Frances", "Christian", "Elaine", "Shayna", "Aniya", "Mollie", "Ryan", "Essence", "Simone", "Kyleigh", "Nikki", "Anya", "Reyna", "Savanah", "Kaylyn", "Nicolette", "Abbie", "Montana", "Kailyn", "Itzel", "Leila", "Cayla", "Stacy", "Robin", "Araceli", "Candace", "Dulce", "Noemi", "Aleah", "Jewel", "Ally", "Mara", "Nayeli", "Karlee", "Keely", "Micaela", "Alisa", "Desirae", "Leanna", "Antonia", "Judith", "Brynn", "Jaelyn", "Raegan", "Katelin", "Sienna", "Celia", "Yvette", "Juliet", "Anika", "Emilia", "Calista", "Carlee", "Eileen", "Kianna", "Thalia", "Rylie", "Rosemary", "Daphne", "Kacie", "Karli", "Micah", "Ericka", "Jadyn", "Lyndsey", "Hana", "Haylie", "Madilyn", "Blanca", "Laila", "Kayley", "Katarina", "Kellie", "Maribel", "Sandy", "Joselyn", "Kaelyn", "Kathy", "Madisen", "Carson", "Margarita", "Stella", "Juliette", "Devon", "Bria", "Camila", "Donna", "Helena", "Lea", "Jazlyn", "Jazmyn", "Skyla", "Christy", "Joyce", "Katharine", "Karlie", "Lexus", "Alessandra", "Salma", "Delilah", "Moriah", "Beatriz", "Celine", "Lizeth", "Brianne", "Kourtney", "Sydnie", "Mariam", "Stacey", "Robyn", "Hayden", "Janessa", "Kenzie", "Jalyn", "Sheila", "Meaghan", "Aisha", "Shawna", "Jaida", "Estrella", "Marley", "Melinda", "Ayana", "Karly", "Devyn", "Nataly", "Loren", "Rosalinda", "Brielle", "Laney", "Sally", "Lizette", "Tracy", "Lilian", "Rebeca", "Chandler", "Jenifer", "Diane", "Valentina", "America", "Candice", "Abigayle", "Susana", "Aliya", "Casandra", "Harmony", "Jacey", "Alena", "Aylin", "Carol", "Shea", "Stephany", "Aniyah", "Zoie", "Jackeline", "Alia", "Gwendolyn", "Savana", "Damaris", "Violet", "Marian", "Anita", "Jaime", "Alexandrea", "Dorothy", "Jaiden", "Kristine", "Carli", "Gretchen", "Janice", "Annette", "Mariela", "Amani", "Maura", "Bella", "Kaylynn", "Lila", "Armani", "Anissa", "Aubree", "Kelsi", "Greta", "Kaya", "Kayli", "Lillie", "Willow", "Ansley", "Catalina", "Lia", "Maci", "Mattie", "Celina", "Shyann", "Alysa", "Jaquelin", "Quinn", "Cecelia", "Kallie", "Kasandra", "Chaya", "Hailie", "Haven", "Maegan", "Maeve", "Rocio", "Yolanda", "Christa", "Gabriel", "Kari", "Noelia", "Jeanette", "Kaylah", "Marianna", "Nya", "Kennedi", "Presley", "Yadira", "Elissa", "Nyah", "Shaina", "Reilly", "Alize", "Amara", "Arlene", "Izabella", "Lyric", "Aiyana", "Allyssa", "Drew", "Rachelle", "Adeline", "Jacklyn", "Jesse", "Citlalli", "Giovanna", "Liana", "Brook", "Graciela", "Princess", "Selina", "Chanel", "Elyse", "Cali", "Berenice", "Iliana", "Jolie", "Annalise", "Caitlynn", "Christiana", "Sarina", "Cortney", "Darlene", "Dasia", "London", "Yvonne", "Karley", "Shaylee", "Kristy", "Myah", "Ryleigh", "Amira", "Juanita", "Dariana", "Teagan", "Kiarra", "Ryann", "Yamilet", "Sheridan", "Alexys", "Baby", "Kacey", "Shakira", "Dianna", "Lara", "Isabela", "Reina", "Shirley", "Jaycee", "Silvia", "Tatianna", "Eryn", "Ingrid", "Keara", "Randi", "Reanna", "Kalyn", "Lisette", "Monserrat", "Abril", "Ivana", "Lori", "Darby", "Kaela", "Maranda", "Parker", "Darian", "Jasmyn", "Jaylin", "Katia", "Ayla", "Bridgette", "Elyssa", "Hillary", "Kinsey", "Yazmin", "Caleigh", "Rita", "Asha", "Dayana", "Nikita", "Chantel", "Reese", "Stefanie", "Nadine", "Samara", "Unique", "Michele", "Sonya", "Hazel", "Patience", "Cielo", "Mireya", "Paloma", "Aryanna", "Magdalena", "Anaya", "Dallas", "Joelle", "Norma", "Arely", "Kaia", "Misty", "Taya", "Deasia", "Trisha", "Elsa", "Joana", "Alysha", "Aracely", "Bryana", "Dawn", "Alex", "Brionna", "Katerina", "Ali", "Bonnie", "Hadley", "Martina", "Maryam", "Jazmyne", "Shaniya", "Alycia", "Dejah", "Emmalee", "Estefania", "Jakayla", "Lilliana", "Nyasia", "Anjali", "Daisha", "Myra", "Amiya", "Belen", "Jana", "Aja", "Saige", "Annabel", "Scarlett", "Destany", "Joanne", "Aliza", "Ashly", "Cydney", "Fabiola", "Gia", "Keira", "Roxanne", "Kaci", "Abigale", "Abagail", "Janiya", "Odalys", "Aria", "Daija", "Delia", "Kameron", "Raina", "Ashtyn", "Dayna", "Katy", "Lourdes", "Emerald", "Kirstin", "Marlee", "Neha", "Beatrice", "Blair", "Kori", "Luisa", "Yasmeen", "Annamarie", "Breonna", "Jena", "Leann", "Rhianna", "Yessenia", "Breanne", "Katlynn", "Laisha", "Mandy", "Amina", "Jailyn", "Jayde", "Jill", "Kaylan", "Kenna", "Antoinette", "Rayna", 
        "Sky", "Iyana", "Keeley", "Kenia", "Maiya", "Melisa", "Adrian", "Marlen", "Jacob", "Michael", "Matthew", "Joshua", 
        "Christopher", "Nicholas", "Andrew", "Joseph", "Daniel", "Tyler", "William", "Brandon", "Ryan", "John", "Zachary", 
        "David", 
        "Anthony", "James", "Justin", "Alexander", "Jonathan", "Christian", "Austin", "Dylan", "Ethan", "Benjamin", "Noah", 
        "Samuel", "Robert", "Nathan", "Cameron", "Kevin", "Thomas", "Jose", "Hunter", "Jordan", "Kyle", "Caleb", "Jason", "Logan", "Aaron", "Eric", "Brian", "Gabriel", "Adam", "Jack", "Isaiah", "Juan", "Luis", "Connor", "Charles", "Elijah", "Isaac", "Steven", "Evan", "Jared", "Sean", "Timothy", "Luke", "Cody", "Nathaniel", "Alex", "Seth", "Mason", "Richard", "Carlos", "Angel", "Patrick", "Devin", "Bryan", "Cole", "Jackson", "Ian", "Garrett", "Trevor", "Jesus", "Chase", "Adrian", "Mark", "Blake", "Sebastian", "Antonio", "Lucas", "Jeremy", "Gavin", "Miguel", "Julian", "Dakota", "Alejandro", "Jesse", "Dalton", "Bryce", "Tanner", "Kenneth", "Stephen", "Jake", "Victor", "Spencer", "Marcus", "Paul", "Brendan", "Jeremiah", "Xavier", "Jeffrey", "Tristan", "Jalen", "Jorge", "Edward", "Riley", "Colton", "Wyatt", "Joel", "Maxwell", "Aidan", "Travis", "Shane", "Colin", "Dominic", "Carson", "Vincent", "Derek", "Oscar", "Grant", "Eduardo", "Peter", "Henry", "Parker", "Collin", "Hayden", "George", "Bradley", "Mitchell", "Devon", "Ricardo", "Shawn", "Taylor", "Nicolas", "Gregory", "Francisco", "Liam", "Kaleb", "Preston", "Erik", "Alexis", "Owen", "Omar", "Diego", "Dustin", "Corey", "Fernando", "Clayton", "Carter", "Ivan", "Jaden", "Javier", "Alec", "Johnathan", "Scott", "Manuel", "Cristian", "Alan", "Raymond", "Brett", "Max", "Andres", "Gage", "Mario", "Dawson", "Dillon", "Cesar", "Wesley", "Levi", "Jakob", "Chandler", "Martin", "Malik", "Edgar", "Sergio", "Trenton", "Josiah", "Nolan", "Marco", "Peyton", "Harrison", "Hector", "Micah", "Roberto", "Drew", "Brady", "Erick", "Conner", "Jonah", "Casey", "Jayden", "Edwin", "Emmanuel", "Andre", "Phillip", "Brayden", "Landon", "Giovanni", "Bailey", "Ronald", "Braden", "Damian", "Donovan", "Ruben", "Frank", "Gerardo", "Pedro", "Andy", "Chance", "Abraham", "Calvin", "Trey", "Cade", "Donald", "Derrick", "Payton", "Darius", "Enrique", "Keith", "Raul", "Jaylen", "Troy", "Jonathon", "Cory", "Marc", "Eli", "Skyler", "Rafael", "Trent", "Griffin", "Colby", "Johnny", "Chad", "Armando", "Kobe", "Caden", "Marcos", "Cooper", "Elias", "Brenden", "Israel", "Avery", "Zane", "Dante", "Josue", "Zackary", "Allen", "Mathew", "Dennis", "Leonardo", "Ashton", "Philip", "Julio", "Miles", "Damien", "Ty", "Gustavo", "Drake", "Jaime", "Simon", "Jerry", "Curtis", "Kameron", "Lance", "Brock", "Bryson", "Alberto", "Dominick", "Jimmy", "Kaden", "Douglas", "Gary", "Brennan", "Zachery", "Randy", "Louis", "Larry", "Nickolas", "Albert", "Tony", "Fabian", "Keegan", "Saul", "Danny", "Tucker", "Myles", "Damon", "Arturo", "Corbin", "Deandre", "Ricky", "Kristopher", "Lane", "Pablo", "Darren", "Jarrett", "Zion", "Alfredo", "Micheal", "Angelo", "Carl", "Oliver", "Kyler", "Tommy", "Walter", "Dallas", "Jace", "Quinn", "Theodore", "Grayson", "Lorenzo", "Joe", "Arthur", "Bryant", "Roman", "Brent", "Russell", "Ramon", "Lawrence", "Moises", "Aiden", "Quentin", "Jay", "Tyrese", "Tristen", "Emanuel", "Salvador", "Terry", "Morgan", "Jeffery", "Esteban", "Tyson", "Braxton", "Branden", "Marvin", "Brody", "Craig", "Ismael", "Rodney", "Isiah", "Marshall", "Maurice", "Ernesto", "Emilio", "Brendon", "Kody", "Eddie", "Malachi", "Abel", "Keaton", "Jon", "Shaun", "Skylar", "Ezekiel", "Nikolas", "Santiago", "Kendall", "Axel", "Camden", "Trevon", "Bobby", "Conor", "Jamal", "Lukas", "Malcolm", "Zackery", "Jayson", "Javon", "Roger", "Reginald", "Zachariah", "Desmond", "Felix", "Johnathon", "Dean", "Quinton", "Ali", "Davis", "Gerald", "Rodrigo", "Demetrius", "Billy", "Rene", "Reece", "Kelvin", "Leo", "Justice", "Chris", "Guillermo", "Kevon", "Steve", "Frederick", "Clay", "Weston", "Dorian", "Hugo", "Roy", "Orlando", "Terrance", "Kai", "Khalil", "Graham", "Noel", "Willie", "Nathanael", "Terrell", "Tyrone", "Camron", "Mauricio", "Amir", "Nelson", "Darian", "Jarod", "Kade", "Reese", "Kristian", "Garret", "Rodolfo", "Marquis", "Dane", "Felipe", "Todd", "Elian", "Walker", "Mateo", "Jaylon", "Kenny", "Ezra", "Bruce", "Damion", "Ross", "Francis", "Tate", "Reid", "Warren", "Byron", "Randall", "Bennett", "Jermaine", "Triston", "Harley", "Jaquan", "Jessie", "Duncan", "Franklin", "Reed", "Charlie", "Blaine", "Braeden", "Holden", "Ahmad", "Issac", "Melvin", "Moses", "Kendrick", "Sawyer", "Solomon", "Sam", "Alvin", "Cedric", "Jaylin", "Jordon", "Mohammad", "Beau", "Elliot", "Lee", "Darrell", "Jarred", "Mohamed", "Davion", "Wade", "Tomas", "Uriel", "Jaxon", "Deven", "Maximilian", "Gilberto", "Rogelio", "Ronnie", "Julius", "Allan", "Joey", "Brayan", "Deshawn", "Terrence", "Noe", "Alfonso", "Ahmed", "Tyree", "Tyrell", "Jerome", "Devan", "Neil", "Ramiro", "Pierce", "Davon", "Devonte", "Leon", "Jamie", "Adan", "Eugene", "Stanley", "Wayne", "Marlon", "Leonard", "Quincy", "Will", "Alvaro", "Ernest", "Harry", "Jonas", "Addison", "Ray", "Alonzo", "Jadon", "Keyshawn", "Rolando", "Mohammed", "Tristin", "Donte", "Leonel", "Dominique", "Wilson", "Gilbert", "Kieran", "Coby", "Dangelo", "Colten", "Keenan", "Koby", "Jarrod", "Dale", "Toby", "Dwayne", "Harold", "Elliott", "Osvaldo", "Cyrus", "Kolby", "Sage", "Coleman", "Declan", "Adolfo", "Ariel", "Brennen", "Darryl", "Trace", "Efrain", "Orion", "Rudy", "Shamar", "Keshawn", "Ulises", "Darien", "Braydon", "Ben", "Vicente", "Nasir", "Dayton", "Joaquin", "Karl", "Dandre", "Isaias", "Cullen", "Rylan", "Sterling", "Quintin", "Stefan", "Brice", "Lewis", "Gunnar", "Humberto", "Alfred", "Nigel", "Asher", "Agustin", "Daquan", "Easton", "Salvatore", "Jaron", "Nathanial", "Ralph", "Everett", "Tobias", "Hudson", "Marquise", "Glenn", "Antoine", "Jasper", "Elvis", "Kane", "Sidney", "Aron", "Ezequiel", "Tylor", "Dashawn", "Devyn", "Mike", "Silas", "Jaiden", "Jayce", "Deonte", "Romeo", "Deon", "Cristopher", "Freddy", "Kurt", "Kolton", "River", "August", "Clarence", "Roderick", "Derick", "Jamar", "Raphael", "Kareem", "Muhammad", "Rohan", "Demarcus", "Sheldon", "Cayden", "Markus", "Luca", "Tre", "Jean", "Titus", "Jamison", "Rory", "Brad", "Clinton", "Jaylan", "Emiliano", "Jevon", "Julien", "Lamar", "Alonso", "Cordell", "Gordon", "Ignacio", "Cruz", "Jett", "Keon", "Baby", "Rashad", "Tariq", "Armani", "Milton", "Deangelo", "Geoffrey", "Elisha", "Moshe", "Asa", "Bernard", "Bret", "Darion", "Darnell", "Izaiah", "Irvin", "Jairo", "Howard", "Aldo", "Norman", "Zechariah", "Ayden", "Garrison", "Stuart", "Travon", "Kellen", "Shemar", "Dillan", "Junior", "Darrius", "Rhett", "Barry", "Kamron", "Jude", "Rigoberto", "Amari", "Jovan", "Perry", "Octavio", "Kole", "Misael", "Hassan", "Jaren", "Latrell", "Roland", "Quinten", "German", "Ibrahim", "Justus", "Gonzalo", "Nehemiah", "Forrest", "Mackenzie", "Talon", "Anton", "Chaz", "Leroy", "Guadalupe", "Winston", "Antwan", "Austen", "Brooks", "Conrad", "Greyson", "Dion", "Lincoln", "Earl", "Jaydon", "Landen", "Gunner", "Brenton", "Jefferson", "Fredrick", "Kurtis", "Maximillian", "Stephan", "Stone", "Shannon", "Shayne", "Stephon", "Karson", "Nestor", "Tristian", "Frankie", "Gianni", "Keagan", "Dimitri", "Kory", "Zakary", "Daryl", "Donavan", "Draven", "Jameson", "Clifton", "Emmett", "Cortez", "Destin", "Jamari", "Dallin", "Estevan", "Grady", "Davin", "Santos", "Marcel", "Carlton", "Dylon", "Mitchel", "Clifford", "Syed", "Dexter", "Adonis", "Keyon", "Reynaldo", "Devante", "Arnold", "Clark", "Kasey", "Sammy", "Thaddeus", "Glen", "Jarvis", "Nick", "Ulysses", "Garett", "Infant", "Keanu", "Kenyon", "Dwight", "Kent", "Denzel", "Lamont", "Houston", "Layne", "Darin", "Jorden", "Anderson", "Kayden", "Khalid", "Antony", "Deondre", "Ellis", "Marquez", "Ari", "Cornelius", "Reuben", "Austyn", "Brycen", "Abram", "Remington", "Braedon", "Hamza", "Ryder", "Zaire", "Terence", "Guy", "Jamel", "Kelly", "Porter", "Tevin", "Alexandro", "Dario", "Jordy", "Trever", "Jackie", "Judah", "Keven", "Raymundo", "Cristobal", "Josef", "Paris", "Colt", "Giancarlo", "Rahul", "Savion", "Deshaun", "Josh", "Korey", "Gerard", "Jacoby", "Lonnie", "Reilly", "Seamus", "Don", "Giovanny", "Jamil", "Kristofer", "Samir", "Vernon", "Benny", "Dominik", "Finn", "Jan", "Kaiden", "Cale", "Irving", "Jaxson", "Marcelo", "Nico", "Rashawn", "Aubrey", "Gaven", "Jabari", "Sincere", "Kirk", "Maximus", "Mikel", "Davonte", "Elmer", "Heath", "Justyn", "Kadin", "Alden", "Kelton", "Brandan", "Courtney", "Camren", "Dewayne", "Duane", "Maverick", "Darrin", "Darrion", "Nikhil", "Sonny", "Abdullah", "Chaim", "Nathen", "Xzavier", "Bronson", "Efren", "Jovani", "Phoenix", "Reagan", "Aden", "Blaze", "Gideon", "Luciano", "Royce", "Tyrek", "Tyshawn", "Deontae", "Fidel", "Gaige", "Neal", "Ronaldo", "Matteo", "Prince", "Rickey", "Deion", "Denver", "Benito", "London", "Samson", "Bernardo", "Raven", "Simeon", "Turner", "Carlo", "Gino", "Johan", "Rocky", "Ryley", "Domenic", "Hugh", "Trystan", "Emerson", "Joan", "Trevion", "Heriberto", "Marques", "Raheem", "Tyreek", "Vaughn", "Clint", "Nash", "Mariano", "Myron", "Ladarius", "Lloyd", "Omari", "Pierre", "Keshaun", "Rick", "Xander", "Amos", "Eliseo", "Jeff", "Bradly", "Freddie", "Kavon", "Mekhi", "Sabastian", "Shea", "Dan", "Adrien", "Alessandro", "Blaise", "Isai", "Kian", "Maximiliano", "Paxton", "Rasheed", "Brodie", "Donnie", "Isidro", "Jaeden", "Javion", "Jimmie", "Johnnie", "Kennedy", "Tyrique", "Andreas", "Augustus", "Jalon", "Jamir", "Valentin", "Korbin", "Lawson", "Maxim", "Fred", "Herbert", "Bruno", "Donavon", "Javonte", "Ean", "Kamren", "Rowan", "Alek", "Brandyn", "Demarco", "Harvey", "Hernan", "Alexzander", "Bo", "Branson", "Brennon", "Genaro", "Jamarcus", "Aric", "Barrett", "Rey", "Braiden", "Brant", "Dontae", "Jovany", "Kale", "Nicklaus", "Zander", "Dillion", "Donnell", "Kylan", "Treyvon", "Vincenzo", "Dayne", "Francesco", "Isaak"
    ];

    public function picker(){
        $counrty = [
            ['name' => 'Afghanistan', 'code' => 'AF'], 
            ['name' => 'Åland Islands', 'code' => 'AX'], 
            ['name' => 'Albania', 'code' => 'AL'], 
            ['name' => 'Algeria', 'code' => 'DZ'], 
            ['name' => 'American Samoa', 'code' => 'AS'], 
            ['name' => 'AndorrA', 'code' => 'AD'], 
            ['name' => 'Angola', 'code' => 'AO'], 
            ['name' => 'Anguilla', 'code' => 'AI'], 
            ['name' => 'Antarctica', 'code' => 'AQ'], 
            ['name' => 'Antigua and Barbuda', 'code' => 'AG'], 
            ['name' => 'Argentina', 'code' => 'AR'], 
            ['name' => 'Armenia', 'code' => 'AM'], 
            ['name' => 'Aruba', 'code' => 'AW'], 
            ['name' => 'Australia', 'code' => 'AU'], 
            ['name' => 'Austria', 'code' => 'AT'], 
            ['name' => 'Azerbaijan', 'code' => 'AZ'], 
            ['name' => 'Bahamas', 'code' => 'BS'], 
            ['name' => 'Bahrain', 'code' => 'BH'], 
            ['name' => 'Bangladesh', 'code' => 'BD'], 
            ['name' => 'Barbados', 'code' => 'BB'], 
            ['name' => 'Belarus', 'code' => 'BY'], 
            ['name' => 'Belgium', 'code' => 'BE'], 
            ['name' => 'Belize', 'code' => 'BZ'], 
            ['name' => 'Benin', 'code' => 'BJ'], 
            ['name' => 'Bermuda', 'code' => 'BM'], 
            ['name' => 'Bhutan', 'code' => 'BT'], 
            ['name' => 'Bolivia', 'code' => 'BO'], 
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'], 
            ['name' => 'Botswana', 'code' => 'BW'], 
            ['name' => 'Bouvet Island', 'code' => 'BV'], 
            ['name' => 'Brazil', 'code' => 'BR'], 
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO'], 
            ['name' => 'Brunei Darussalam', 'code' => 'BN'], 
            ['name' => 'Bulgaria', 'code' => 'BG'], 
            ['name' => 'Burkina Faso', 'code' => 'BF'], 
            ['name' => 'Burundi', 'code' => 'BI'], 
            ['name' => 'Cambodia', 'code' => 'KH'], 
            ['name' => 'Cameroon', 'code' => 'CM'], 
            ['name' => 'Canada', 'code' => 'CA'], 
            ['name' => 'Cape Verde', 'code' => 'CV'], 
            ['name' => 'Cayman Islands', 'code' => 'KY'], 
            ['name' => 'Central African Republic', 'code' => 'CF'], 
            ['name' => 'Chad', 'code' => 'TD'], 
            ['name' => 'Chile', 'code' => 'CL'], 
            ['name' => 'China', 'code' => 'CN'], 
            ['name' => 'Christmas Island', 'code' => 'CX'], 
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'], 
            ['name' => 'Colombia', 'code' => 'CO'], 
            ['name' => 'Comoros', 'code' => 'KM'], 
            ['name' => 'Congo', 'code' => 'CG'], 
            ['name' => 'Congo, The Democratic Republic of the', 'code' => 'CD'], 
            ['name' => 'Cook Islands', 'code' => 'CK'], 
            ['name' => 'Costa Rica', 'code' => 'CR'], 
            ['name' => 'Cote D\'Ivoire', 'code' => 'CI'], 
            ['name' => 'Croatia', 'code' => 'HR'], 
            ['name' => 'Cuba', 'code' => 'CU'], 
            ['name' => 'Cyprus', 'code' => 'CY'], 
            ['name' => 'Czech Republic', 'code' => 'CZ'], 
            ['name' => 'Denmark', 'code' => 'DK'], 
            ['name' => 'Djibouti', 'code' => 'DJ'], 
            ['name' => 'Dominica', 'code' => 'DM'], 
            ['name' => 'Dominican Republic', 'code' => 'DO'], 
            ['name' => 'Ecuador', 'code' => 'EC'], 
            ['name' => 'Egypt', 'code' => 'EG'], 
            ['name' => 'El Salvador', 'code' => 'SV'], 
            ['name' => 'Equatorial Guinea', 'code' => 'GQ'], 
            ['name' => 'Eritrea', 'code' => 'ER'], 
            ['name' => 'Estonia', 'code' => 'EE'], 
            ['name' => 'Ethiopia', 'code' => 'ET'], 
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'], 
            ['name' => 'Faroe Islands', 'code' => 'FO'], 
            ['name' => 'Fiji', 'code' => 'FJ'], 
            ['name' => 'Finland', 'code' => 'FI'], 
            ['name' => 'France', 'code' => 'FR'], 
            ['name' => 'French Guiana', 'code' => 'GF'], 
            ['name' => 'French Polynesia', 'code' => 'PF'], 
            ['name' => 'French Southern Territories', 'code' => 'TF'], 
            ['name' => 'Gabon', 'code' => 'GA'], 
            ['name' => 'Gambia', 'code' => 'GM'], 
            ['name' => 'Georgia', 'code' => 'GE'], 
            ['name' => 'Germany', 'code' => 'DE'], 
            ['name' => 'Ghana', 'code' => 'GH'], 
            ['name' => 'Gibraltar', 'code' => 'GI'], 
            ['name' => 'Greece', 'code' => 'GR'], 
            ['name' => 'Greenland', 'code' => 'GL'], 
            ['name' => 'Grenada', 'code' => 'GD'], 
            ['name' => 'Guadeloupe', 'code' => 'GP'], 
            ['name' => 'Guam', 'code' => 'GU'], 
            ['name' => 'Guatemala', 'code' => 'GT'], 
            ['name' => 'Guernsey', 'code' => 'GG'], 
            ['name' => 'Guinea', 'code' => 'GN'], 
            ['name' => 'Guinea-Bissau', 'code' => 'GW'], 
            ['name' => 'Guyana', 'code' => 'GY'], 
            ['name' => 'Haiti', 'code' => 'HT'], 
            ['name' => 'Heard Island and Mcdonald Islands', 'code' => 'HM'], 
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA'], 
            ['name' => 'Honduras', 'code' => 'HN'], 
            ['name' => 'Hong Kong', 'code' => 'HK'], 
            ['name' => 'Hungary', 'code' => 'HU'], 
            ['name' => 'Iceland', 'code' => 'IS'], 
            ['name' => 'India', 'code' => 'IN'], 
            ['name' => 'Indonesia', 'code' => 'ID'], 
            ['name' => 'Iran, Islamic Republic Of', 'code' => 'IR'], 
            ['name' => 'Iraq', 'code' => 'IQ'], 
            ['name' => 'Ireland', 'code' => 'IE'], 
            ['name' => 'Isle of Man', 'code' => 'IM'], 
            ['name' => 'Israel', 'code' => 'IL'], 
            ['name' => 'Italy', 'code' => 'IT'], 
            ['name' => 'Jamaica', 'code' => 'JM'], 
            ['name' => 'Japan', 'code' => 'JP'], 
            ['name' => 'Jersey', 'code' => 'JE'], 
            ['name' => 'Jordan', 'code' => 'JO'], 
            ['name' => 'Kazakhstan', 'code' => 'KZ'], 
            ['name' => 'Kenya', 'code' => 'KE'], 
            ['name' => 'Kiribati', 'code' => 'KI'], 
            ['name' => 'Korea, Democratic People\'S Republic of', 'code' => 'KP'], 
            ['name' => 'Korea, Republic of', 'code' => 'KR'], 
            ['name' => 'Kuwait', 'code' => 'KW'], 
            ['name' => 'Kyrgyzstan', 'code' => 'KG'], 
            ['name' => 'Lao People\'S Democratic Republic', 'code' => 'LA'], 
            ['name' => 'Latvia', 'code' => 'LV'], 
            ['name' => 'Lebanon', 'code' => 'LB'], 
            ['name' => 'Lesotho', 'code' => 'LS'], 
            ['name' => 'Liberia', 'code' => 'LR'], 
            ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LY'], 
            ['name' => 'Liechtenstein', 'code' => 'LI'], 
            ['name' => 'Lithuania', 'code' => 'LT'], 
            ['name' => 'Luxembourg', 'code' => 'LU'], 
            ['name' => 'Macao', 'code' => 'MO'], 
            ['name' => 'Macedonia, The Former Yugoslav Republic of', 'code' => 'MK'], 
            ['name' => 'Madagascar', 'code' => 'MG'], 
            ['name' => 'Malawi', 'code' => 'MW'], 
            ['name' => 'Malaysia', 'code' => 'MY'], 
            ['name' => 'Maldives', 'code' => 'MV'], 
            ['name' => 'Mali', 'code' => 'ML'], 
            ['name' => 'Malta', 'code' => 'MT'], 
            ['name' => 'Marshall Islands', 'code' => 'MH'], 
            ['name' => 'Martinique', 'code' => 'MQ'], 
            ['name' => 'Mauritania', 'code' => 'MR'], 
            ['name' => 'Mauritius', 'code' => 'MU'], 
            ['name' => 'Mayotte', 'code' => 'YT'], 
            ['name' => 'Mexico', 'code' => 'MX'], 
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM'], 
            ['name' => 'Moldova, Republic of', 'code' => 'MD'], 
            ['name' => 'Monaco', 'code' => 'MC'], 
            ['name' => 'Mongolia', 'code' => 'MN'], 
            ['name' => 'Montserrat', 'code' => 'MS'], 
            ['name' => 'Morocco', 'code' => 'MA'], 
            ['name' => 'Mozambique', 'code' => 'MZ'], 
            ['name' => 'Myanmar', 'code' => 'MM'], 
            ['name' => 'Namibia', 'code' => 'NA'], 
            ['name' => 'Nauru', 'code' => 'NR'], 
            ['name' => 'Nepal', 'code' => 'NP'], 
            ['name' => 'Netherlands', 'code' => 'NL'], 
            ['name' => 'Netherlands Antilles', 'code' => 'AN'], 
            ['name' => 'New Caledonia', 'code' => 'NC'], 
            ['name' => 'New Zealand', 'code' => 'NZ'], 
            ['name' => 'Nicaragua', 'code' => 'NI'], 
            ['name' => 'Niger', 'code' => 'NE'], 
            ['name' => 'Nigeria', 'code' => 'NG'], 
            ['name' => 'Niue', 'code' => 'NU'], 
            ['name' => 'Norfolk Island', 'code' => 'NF'], 
            ['name' => 'Northern Mariana Islands', 'code' => 'MP'], 
            ['name' => 'Norway', 'code' => 'NO'], 
            ['name' => 'Oman', 'code' => 'OM'], 
            ['name' => 'Pakistan', 'code' => 'PK'], 
            ['name' => 'Palau', 'code' => 'PW'], 
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS'], 
            ['name' => 'Panama', 'code' => 'PA'], 
            ['name' => 'Papua New Guinea', 'code' => 'PG'], 
            ['name' => 'Paraguay', 'code' => 'PY'], 
            ['name' => 'Peru', 'code' => 'PE'], 
            ['name' => 'Philippines', 'code' => 'PH'], 
            ['name' => 'Pitcairn', 'code' => 'PN'], 
            ['name' => 'Poland', 'code' => 'PL'], 
            ['name' => 'Portugal', 'code' => 'PT'], 
            ['name' => 'Puerto Rico', 'code' => 'PR'], 
            ['name' => 'Qatar', 'code' => 'QA'], 
            ['name' => 'Reunion', 'code' => 'RE'], 
            ['name' => 'Romania', 'code' => 'RO'], 
            ['name' => 'Russian Federation', 'code' => 'RU'], 
            ['name' => 'RWANDA', 'code' => 'RW'], 
            ['name' => 'Saint Helena', 'code' => 'SH'], 
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN'], 
            ['name' => 'Saint Lucia', 'code' => 'LC'], 
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'], 
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'], 
            ['name' => 'Samoa', 'code' => 'WS'], 
            ['name' => 'San Marino', 'code' => 'SM'], 
            ['name' => 'Sao Tome and Principe', 'code' => 'ST'], 
            ['name' => 'Saudi Arabia', 'code' => 'SA'], 
            ['name' => 'Senegal', 'code' => 'SN'], 
            ['name' => 'Serbia and Montenegro', 'code' => 'CS'], 
            ['name' => 'Seychelles', 'code' => 'SC'], 
            ['name' => 'Sierra Leone', 'code' => 'SL'], 
            ['name' => 'Singapore', 'code' => 'SG'], 
            ['name' => 'Slovakia', 'code' => 'SK'], 
            ['name' => 'Slovenia', 'code' => 'SI'], 
            ['name' => 'Solomon Islands', 'code' => 'SB'], 
            ['name' => 'Somalia', 'code' => 'SO'], 
            ['name' => 'South Africa', 'code' => 'ZA'], 
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'], 
            ['name' => 'Spain', 'code' => 'ES'], 
            ['name' => 'Sri Lanka', 'code' => 'LK'], 
            ['name' => 'Sudan', 'code' => 'SD'], 
            ['name' => 'Suriname', 'code' => 'SR'], 
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'], 
            ['name' => 'Swaziland', 'code' => 'SZ'], 
            ['name' => 'Sweden', 'code' => 'SE'], 
            ['name' => 'Switzerland', 'code' => 'CH'], 
            ['name' => 'Syrian Arab Republic', 'code' => 'SY'], 
            ['name' => 'Taiwan, Province of China', 'code' => 'TW'], 
            ['name' => 'Tajikistan', 'code' => 'TJ'], 
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ'], 
            ['name' => 'Thailand', 'code' => 'TH'], 
            ['name' => 'Timor-Leste', 'code' => 'TL'], 
            ['name' => 'Togo', 'code' => 'TG'], 
            ['name' => 'Tokelau', 'code' => 'TK'], 
            ['name' => 'Tonga', 'code' => 'TO'], 
            ['name' => 'Trinidad and Tobago', 'code' => 'TT'], 
            ['name' => 'Tunisia', 'code' => 'TN'], 
            ['name' => 'Turkey', 'code' => 'TR'], 
            ['name' => 'Turkmenistan', 'code' => 'TM'], 
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC'], 
            ['name' => 'Tuvalu', 'code' => 'TV'], 
            ['name' => 'Uganda', 'code' => 'UG'], 
            ['name' => 'Ukraine', 'code' => 'UA'], 
            ['name' => 'United Arab Emirates', 'code' => 'AE'], 
            ['name' => 'United Kingdom', 'code' => 'GB'], 
            ['name' => 'United States', 'code' => 'US'], 
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM'], 
            ['name' => 'Uruguay', 'code' => 'UY'], 
            ['name' => 'Uzbekistan', 'code' => 'UZ'], 
            ['name' => 'Vanuatu', 'code' => 'VU'], 
            ['name' => 'Venezuela', 'code' => 'VE'], 
            ['name' => 'Viet Nam', 'code' => 'VN'], 
            ['name' => 'Virgin Islands, British', 'code' => 'VG'], 
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'], 
            ['name' => 'Wallis and Futuna', 'code' => 'WF'], 
            ['name' => 'Western Sahara', 'code' => 'EH'], 
            ['name' => 'Yemen', 'code' => 'YE'], 
            ['name' => 'Zambia', 'code' => 'ZM'], 
            ['name' => 'Zimbabwe', 'code' => 'ZW'] 
        ];
        
        $names = [
            "Emily", "Hannah", "Madison", "Ashley", "Sarah", "Alexis", "Samantha", "Jessica", 
            "Elizabeth", "Taylor", "Lauren", "Alyssa", "Kayla", "Abigail", "Brianna", "Olivia", "Emma", 
            "Megan", "Grace", "Victoria", "Rachel", "Anna", "Sydney", "Destiny", "Morgan", "Jennifer", 
            "Jasmine", "Haley", "Julia", "Kaitlyn", "Nicole", "Amanda", "Katherine", "Natalie", "Hailey", 
            "Alexandra", "Savannah", "Chloe", "Rebecca", "Stephanie", "Maria", "Sophia", "Mackenzie", "Allison", 
            "Isabella", "Mary", "Amber", "Danielle", "Gabrielle", "Jordan", "Brooke", "Michelle", "Sierra", 
            "Katelyn", "Andrea", "Madeline", "Sara", "Kimberly", "Courtney", "Erin", "Brittany", "Vanessa", 
            "Jenna", "Jacqueline", "Caroline", "Faith", "Makayla", "Bailey", "Paige", "Shelby", "Melissa", 
            "Kaylee", "Christina", "Trinity", "Mariah", "Caitlin", "Autumn", "Marissa", "Angela", "Breanna", 
            "Catherine", "Zoe", "Briana", "Jada", "Laura", "Claire", "Alexa", "Kelsey", "Kathryn", "Leslie", 
            "Alexandria", "Sabrina", "Mia", "Isabel", "Molly", "Katie", "Leah", "Gabriella", "Cheyenne", 
            "Cassandra", "Tiffany", "Erica", "Lindsey", "Kylie", "Amy", "Diana", "Cassidy", "Mikayla", "Ariana",
            "Margaret", "Kelly", "Miranda", "Maya", "Melanie", "Audrey", "Jade", "Gabriela", "Caitlyn", "Angel", 
            "Jillian", "Alicia", "Jocelyn", "Erika", "Lily", "Heather", "Madelyn", "Adriana", "Arianna", "Lillian", 
            "Kiara", "Riley", "Crystal", "Mckenzie", "Meghan", "Skylar", "Ana", "Britney", "Angelica", "Kennedy", 
            "Chelsea", "Daisy", "Kristen", "Veronica", "Isabelle", "Summer", "Hope", "Brittney", "Lydia", "Hayley", 
            "Evelyn", "Bethany", "Shannon", "Karen", "Michaela", "Jamie", "Daniela", "Angelina", "Kaitlin", "Karina", 
            "Sophie", "Sofia", "Diamond", "Payton", "Cynthia", "Alexia", "Valerie", "Monica", "Peyton", "Carly", "Bianca",
            "Hanna", "Brenda", "Rebekah", "Alejandra", "Mya", "Avery", "Brooklyn", "Ashlyn", "Lindsay", "Ava", "Desiree",
            "Alondra", "Camryn", "Ariel", "Naomi", "Jordyn", "Kendra", "Mckenna", "Holly", "Julie", "Kendall", "Kara",
            "Jasmin", "Selena", "Esmeralda", "Amaya", "Kylee", "Maggie", "Makenzie", "Claudia", "Kyra", "Cameron",
            "Karla", "Kathleen", "Abby", "Delaney", "Amelia", "Casey", "Serena", "Savanna", "Aaliyah", "Giselle",
            "Mallory", "April", "Adrianna", "Raven", "Christine", "Kristina", "Nina", "Asia", "Natalia", "Valeria", 
            "Aubrey", "Lauryn", "Kate", "Patricia", "Jazmin", "Rachael", "Katelynn", "Cierra", "Alison", "Nancy", "Macy", 
            "Elena", "Kyla", "Katrina", "Jazmine", "Joanna", "Tara", "Gianna", "Juliana", "Fatima", "Sadie", "Allyson", 
            "Gracie", "Guadalupe", "Genesis", "Yesenia", "Julianna", "Skyler", "Tatiana", "Alexus", "Alana", "Elise", 
            "Kirsten", "Nadia", "Sandra", "Ruby", "Dominique", "Haylee", "Jayla", "Tori", "Cindy", "Ella", "Sidney", 
            "Tessa", "Carolina", "Jaqueline", "Camille", "Carmen", "Whitney", "Vivian", "Priscilla", "Bridget", "Celeste", 
            "Kiana", "Makenna", "Alissa", "Madeleine", "Miriam", "Natasha", "Ciara", "Cecilia", "Kassandra", "Mercedes", 
            "Reagan", "Aliyah", "Josephine", "Charlotte", "Rylee", "Shania", "Kira", "Meredith", "Eva", "Lisa", "Dakota", 
            "Hallie", "Anne", "Rose", "Liliana", "Kristin", "Deanna", "Imani", "Marisa", "Kailey", "Annie", "Nia", "Carolyn", 
            "Anastasia", "Brenna", "Dana", "Shayla", "Ashlee", "Kassidy", "Alaina", "Wendy", "Rosa", "Logan", "Tabitha", "Paola", 
            "Callie", "Addison", "Lucy", "Gillian", "Clarissa", "Esther", "Destinee", "Josie", "Denise", "Katlyn", "Mariana", 
            "Bryanna", "Emilee", "Georgia", "Kamryn", "Deja", "Ashleigh", "Cristina", "Ruth", "Baylee", "Heaven", "Raquel", 
            "Monique", "Teresa", "Helen", "Krystal", "Tiana", "Cassie", "Kayleigh", "Marina", "Ivy", "Heidi", "Clara", "Ashton", "Meagan", "Gina", "Linda", "Gloria", "Jacquelyn", "Ellie", "Jenny", "Renee", "Daniella", "Lizbeth", "Anahi", "Virginia", "Gisselle", "Kaitlynn", "Julissa", "Cheyanne", "Lacey", "Haleigh", "Marie", "Martha", "Eleanor", "Kierra", "Tiara", "Talia", "Eliza", "Kaylie", "Mikaela", "Harley", "Jaden", "Hailee", "Madalyn", "Kasey", "Ashlynn", "Brandi", "Lesly", "Elisabeth", "Allie", "Viviana", "Cara", "Marisol", "India", "Litzy", "Tatyana", "Melody", "Jessie", "Brandy", "Alisha", "Hunter", "Noelle", "Carla", "Francesca", "Tia", "Layla", "Krista", "Zoey", "Carley", "Janet", "Carissa", "Iris", "Susan", "Kaleigh", "Tyler", "Tamara", "Theresa", "Yasmine", "Tatum", "Sharon", "Alice", "Yasmin", "Tamia", "Abbey", "Alayna", "Kali", "Lilly", "Bailee", "Lesley", "Mckayla", "Ayanna", "Serenity", "Karissa", "Precious", "Jane", "Maddison", "Jayda", "Lexi", "Kelsie", "Phoebe", "Halle", "Kiersten", "Kiera", "Tyra", "Annika", "Felicity", "Taryn", "Kaylin", "Ellen", "Kiley", "Jaclyn", "Rhiannon", "Madisyn", "Colleen", "Joy", "Charity", "Pamela", "Tania", "Fiona", "Kaila", "Irene", "Alyson", "Annabelle", "Emely", "Angelique", "Alina", "Johanna", "Regan", "Janelle", "Janae", "Madyson", "Paris", "Justine", "Chelsey", "Sasha", "Paulina", "Mayra", "Zaria", "Skye", "Cora", "Brisa", "Emilie", "Felicia", "Tianna", "Larissa", "Macie", "Aurora", "Sage", "Lucia", "Alma", "Chasity", "Ann", "Deborah", "Nichole", "Jayden", "Alanna", "Malia", "Carlie", "Angie", "Nora", "Sylvia", "Carrie", "Kailee", "Elaina", "Sonia", "Barbara", "Kenya", "Genevieve", "Piper", "Marilyn", "Amari", "Macey", "Marlene", "Julianne", "Tayler", "Brooklynn", "Lorena", "Perla", "Elisa", "Eden", "Kaley", "Leilani", "Miracle", "Devin", "Aileen", "Chyna", "Esperanza", "Athena", "Regina", "Adrienne", "Shyanne", "Luz", "Tierra", "Clare", "Cristal", "Eliana", "Kelli", "Eve", "Sydnee", "Madelynn", "Breana", "Melina", "Arielle", "Justice", "Toni", "Corinne", "Abbigail", "Maia", "Tess", "Ciera", "Ebony", "Lena", "Maritza", "Lexie", "Isis", "Aimee", "Leticia", "Sydni", "Sarai", "Halie", "Alivia", "Destiney", "Laurel", "Edith", "Fernanda", "Carina", "Amya", "Destini", "Aspen", "Nathalie", "Paula", "Tanya", "Tina", "Frances", "Christian", "Elaine", "Shayna", "Aniya", "Mollie", "Ryan", "Essence", "Simone", "Kyleigh", "Nikki", "Anya", "Reyna", "Savanah", "Kaylyn", "Nicolette", "Abbie", "Montana", "Kailyn", "Itzel", "Leila", "Cayla", "Stacy", "Robin", "Araceli", "Candace", "Dulce", "Noemi", "Aleah", "Jewel", "Ally", "Mara", "Nayeli", "Karlee", "Keely", "Micaela", "Alisa", "Desirae", "Leanna", "Antonia", "Judith", "Brynn", "Jaelyn", "Raegan", "Katelin", "Sienna", "Celia", "Yvette", "Juliet", "Anika", "Emilia", "Calista", "Carlee", "Eileen", "Kianna", "Thalia", "Rylie", "Rosemary", "Daphne", "Kacie", "Karli", "Micah", "Ericka", "Jadyn", "Lyndsey", "Hana", "Haylie", "Madilyn", "Blanca", "Laila", "Kayley", "Katarina", "Kellie", "Maribel", "Sandy", "Joselyn", "Kaelyn", "Kathy", "Madisen", "Carson", "Margarita", "Stella", "Juliette", "Devon", "Bria", "Camila", "Donna", "Helena", "Lea", "Jazlyn", "Jazmyn", "Skyla", "Christy", "Joyce", "Katharine", "Karlie", "Lexus", "Alessandra", "Salma", "Delilah", "Moriah", "Beatriz", "Celine", "Lizeth", "Brianne", "Kourtney", "Sydnie", "Mariam", "Stacey", "Robyn", "Hayden", "Janessa", "Kenzie", "Jalyn", "Sheila", "Meaghan", "Aisha", "Shawna", "Jaida", "Estrella", "Marley", "Melinda", "Ayana", "Karly", "Devyn", "Nataly", "Loren", "Rosalinda", "Brielle", "Laney", "Sally", "Lizette", "Tracy", "Lilian", "Rebeca", "Chandler", "Jenifer", "Diane", "Valentina", "America", "Candice", "Abigayle", "Susana", "Aliya", "Casandra", "Harmony", "Jacey", "Alena", "Aylin", "Carol", "Shea", "Stephany", "Aniyah", "Zoie", "Jackeline", "Alia", "Gwendolyn", "Savana", "Damaris", "Violet", "Marian", "Anita", "Jaime", "Alexandrea", "Dorothy", "Jaiden", "Kristine", "Carli", "Gretchen", "Janice", "Annette", "Mariela", "Amani", "Maura", "Bella", "Kaylynn", "Lila", "Armani", "Anissa", "Aubree", "Kelsi", "Greta", "Kaya", "Kayli", "Lillie", "Willow", "Ansley", "Catalina", "Lia", "Maci", "Mattie", "Celina", "Shyann", "Alysa", "Jaquelin", "Quinn", "Cecelia", "Kallie", "Kasandra", "Chaya", "Hailie", "Haven", "Maegan", "Maeve", "Rocio", "Yolanda", "Christa", "Gabriel", "Kari", "Noelia", "Jeanette", "Kaylah", "Marianna", "Nya", "Kennedi", "Presley", "Yadira", "Elissa", "Nyah", "Shaina", "Reilly", "Alize", "Amara", "Arlene", "Izabella", "Lyric", "Aiyana", "Allyssa", "Drew", "Rachelle", "Adeline", "Jacklyn", "Jesse", "Citlalli", "Giovanna", "Liana", "Brook", "Graciela", "Princess", "Selina", "Chanel", "Elyse", "Cali", "Berenice", "Iliana", "Jolie", "Annalise", "Caitlynn", "Christiana", "Sarina", "Cortney", "Darlene", "Dasia", "London", "Yvonne", "Karley", "Shaylee", "Kristy", "Myah", "Ryleigh", "Amira", "Juanita", "Dariana", "Teagan", "Kiarra", "Ryann", "Yamilet", "Sheridan", "Alexys", "Baby", "Kacey", "Shakira", "Dianna", "Lara", "Isabela", "Reina", "Shirley", "Jaycee", "Silvia", "Tatianna", "Eryn", "Ingrid", "Keara", "Randi", "Reanna", "Kalyn", "Lisette", "Monserrat", "Abril", "Ivana", "Lori", "Darby", "Kaela", "Maranda", "Parker", "Darian", "Jasmyn", "Jaylin", "Katia", "Ayla", "Bridgette", "Elyssa", "Hillary", "Kinsey", "Yazmin", "Caleigh", "Rita", "Asha", "Dayana", "Nikita", "Chantel", "Reese", "Stefanie", "Nadine", "Samara", "Unique", "Michele", "Sonya", "Hazel", "Patience", "Cielo", "Mireya", "Paloma", "Aryanna", "Magdalena", "Anaya", "Dallas", "Joelle", "Norma", "Arely", "Kaia", "Misty", "Taya", "Deasia", "Trisha", "Elsa", "Joana", "Alysha", "Aracely", "Bryana", "Dawn", "Alex", "Brionna", "Katerina", "Ali", "Bonnie", "Hadley", "Martina", "Maryam", "Jazmyne", "Shaniya", "Alycia", "Dejah", "Emmalee", "Estefania", "Jakayla", "Lilliana", "Nyasia", "Anjali", "Daisha", "Myra", "Amiya", "Belen", "Jana", "Aja", "Saige", "Annabel", "Scarlett", "Destany", "Joanne", "Aliza", "Ashly", "Cydney", "Fabiola", "Gia", "Keira", "Roxanne", "Kaci", "Abigale", "Abagail", "Janiya", "Odalys", "Aria", "Daija", "Delia", "Kameron", "Raina", "Ashtyn", "Dayna", "Katy", "Lourdes", "Emerald", "Kirstin", "Marlee", "Neha", "Beatrice", "Blair", "Kori", "Luisa", "Yasmeen", "Annamarie", "Breonna", "Jena", "Leann", "Rhianna", "Yessenia", "Breanne", "Katlynn", "Laisha", "Mandy", "Amina", "Jailyn", "Jayde", "Jill", "Kaylan", "Kenna", "Antoinette", "Rayna", 
            "Sky", "Iyana", "Keeley", "Kenia", "Maiya", "Melisa", "Adrian", "Marlen", "Jacob", "Michael", "Matthew", "Joshua", 
            "Christopher", "Nicholas", "Andrew", "Joseph", "Daniel", "Tyler", "William", "Brandon", "Ryan", "John", "Zachary", 
            "David", 
            "Anthony", "James", "Justin", "Alexander", "Jonathan", "Christian", "Austin", "Dylan", "Ethan", "Benjamin", "Noah", 
            "Samuel", "Robert", "Nathan", "Cameron", "Kevin", "Thomas", "Jose", "Hunter", "Jordan", "Kyle", "Caleb", "Jason", "Logan", "Aaron", "Eric", "Brian", "Gabriel", "Adam", "Jack", "Isaiah", "Juan", "Luis", "Connor", "Charles", "Elijah", "Isaac", "Steven", "Evan", "Jared", "Sean", "Timothy", "Luke", "Cody", "Nathaniel", "Alex", "Seth", "Mason", "Richard", "Carlos", "Angel", "Patrick", "Devin", "Bryan", "Cole", "Jackson", "Ian", "Garrett", "Trevor", "Jesus", "Chase", "Adrian", "Mark", "Blake", "Sebastian", "Antonio", "Lucas", "Jeremy", "Gavin", "Miguel", "Julian", "Dakota", "Alejandro", "Jesse", "Dalton", "Bryce", "Tanner", "Kenneth", "Stephen", "Jake", "Victor", "Spencer", "Marcus", "Paul", "Brendan", "Jeremiah", "Xavier", "Jeffrey", "Tristan", "Jalen", "Jorge", "Edward", "Riley", "Colton", "Wyatt", "Joel", "Maxwell", "Aidan", "Travis", "Shane", "Colin", "Dominic", "Carson", "Vincent", "Derek", "Oscar", "Grant", "Eduardo", "Peter", "Henry", "Parker", "Collin", "Hayden", "George", "Bradley", "Mitchell", "Devon", "Ricardo", "Shawn", "Taylor", "Nicolas", "Gregory", "Francisco", "Liam", "Kaleb", "Preston", "Erik", "Alexis", "Owen", "Omar", "Diego", "Dustin", "Corey", "Fernando", "Clayton", "Carter", "Ivan", "Jaden", "Javier", "Alec", "Johnathan", "Scott", "Manuel", "Cristian", "Alan", "Raymond", "Brett", "Max", "Andres", "Gage", "Mario", "Dawson", "Dillon", "Cesar", "Wesley", "Levi", "Jakob", "Chandler", "Martin", "Malik", "Edgar", "Sergio", "Trenton", "Josiah", "Nolan", "Marco", "Peyton", "Harrison", "Hector", "Micah", "Roberto", "Drew", "Brady", "Erick", "Conner", "Jonah", "Casey", "Jayden", "Edwin", "Emmanuel", "Andre", "Phillip", "Brayden", "Landon", "Giovanni", "Bailey", "Ronald", "Braden", "Damian", "Donovan", "Ruben", "Frank", "Gerardo", "Pedro", "Andy", "Chance", "Abraham", "Calvin", "Trey", "Cade", "Donald", "Derrick", "Payton", "Darius", "Enrique", "Keith", "Raul", "Jaylen", "Troy", "Jonathon", "Cory", "Marc", "Eli", "Skyler", "Rafael", "Trent", "Griffin", "Colby", "Johnny", "Chad", "Armando", "Kobe", "Caden", "Marcos", "Cooper", "Elias", "Brenden", "Israel", "Avery", "Zane", "Dante", "Josue", "Zackary", "Allen", "Mathew", "Dennis", "Leonardo", "Ashton", "Philip", "Julio", "Miles", "Damien", "Ty", "Gustavo", "Drake", "Jaime", "Simon", "Jerry", "Curtis", "Kameron", "Lance", "Brock", "Bryson", "Alberto", "Dominick", "Jimmy", "Kaden", "Douglas", "Gary", "Brennan", "Zachery", "Randy", "Louis", "Larry", "Nickolas", "Albert", "Tony", "Fabian", "Keegan", "Saul", "Danny", "Tucker", "Myles", "Damon", "Arturo", "Corbin", "Deandre", "Ricky", "Kristopher", "Lane", "Pablo", "Darren", "Jarrett", "Zion", "Alfredo", "Micheal", "Angelo", "Carl", "Oliver", "Kyler", "Tommy", "Walter", "Dallas", "Jace", "Quinn", "Theodore", "Grayson", "Lorenzo", "Joe", "Arthur", "Bryant", "Roman", "Brent", "Russell", "Ramon", "Lawrence", "Moises", "Aiden", "Quentin", "Jay", "Tyrese", "Tristen", "Emanuel", "Salvador", "Terry", "Morgan", "Jeffery", "Esteban", "Tyson", "Braxton", "Branden", "Marvin", "Brody", "Craig", "Ismael", "Rodney", "Isiah", "Marshall", "Maurice", "Ernesto", "Emilio", "Brendon", "Kody", "Eddie", "Malachi", "Abel", "Keaton", "Jon", "Shaun", "Skylar", "Ezekiel", "Nikolas", "Santiago", "Kendall", "Axel", "Camden", "Trevon", "Bobby", "Conor", "Jamal", "Lukas", "Malcolm", "Zackery", "Jayson", "Javon", "Roger", "Reginald", "Zachariah", "Desmond", "Felix", "Johnathon", "Dean", "Quinton", "Ali", "Davis", "Gerald", "Rodrigo", "Demetrius", "Billy", "Rene", "Reece", "Kelvin", "Leo", "Justice", "Chris", "Guillermo", "Kevon", "Steve", "Frederick", "Clay", "Weston", "Dorian", "Hugo", "Roy", "Orlando", "Terrance", "Kai", "Khalil", "Graham", "Noel", "Willie", "Nathanael", "Terrell", "Tyrone", "Camron", "Mauricio", "Amir", "Nelson", "Darian", "Jarod", "Kade", "Reese", "Kristian", "Garret", "Rodolfo", "Marquis", "Dane", "Felipe", "Todd", "Elian", "Walker", "Mateo", "Jaylon", "Kenny", "Ezra", "Bruce", "Damion", "Ross", "Francis", "Tate", "Reid", "Warren", "Byron", "Randall", "Bennett", "Jermaine", "Triston", "Harley", "Jaquan", "Jessie", "Duncan", "Franklin", "Reed", "Charlie", "Blaine", "Braeden", "Holden", "Ahmad", "Issac", "Melvin", "Moses", "Kendrick", "Sawyer", "Solomon", "Sam", "Alvin", "Cedric", "Jaylin", "Jordon", "Mohammad", "Beau", "Elliot", "Lee", "Darrell", "Jarred", "Mohamed", "Davion", "Wade", "Tomas", "Uriel", "Jaxon", "Deven", "Maximilian", "Gilberto", "Rogelio", "Ronnie", "Julius", "Allan", "Joey", "Brayan", "Deshawn", "Terrence", "Noe", "Alfonso", "Ahmed", "Tyree", "Tyrell", "Jerome", "Devan", "Neil", "Ramiro", "Pierce", "Davon", "Devonte", "Leon", "Jamie", "Adan", "Eugene", "Stanley", "Wayne", "Marlon", "Leonard", "Quincy", "Will", "Alvaro", "Ernest", "Harry", "Jonas", "Addison", "Ray", "Alonzo", "Jadon", "Keyshawn", "Rolando", "Mohammed", "Tristin", "Donte", "Leonel", "Dominique", "Wilson", "Gilbert", "Kieran", "Coby", "Dangelo", "Colten", "Keenan", "Koby", "Jarrod", "Dale", "Toby", "Dwayne", "Harold", "Elliott", "Osvaldo", "Cyrus", "Kolby", "Sage", "Coleman", "Declan", "Adolfo", "Ariel", "Brennen", "Darryl", "Trace", "Efrain", "Orion", "Rudy", "Shamar", "Keshawn", "Ulises", "Darien", "Braydon", "Ben", "Vicente", "Nasir", "Dayton", "Joaquin", "Karl", "Dandre", "Isaias", "Cullen", "Rylan", "Sterling", "Quintin", "Stefan", "Brice", "Lewis", "Gunnar", "Humberto", "Alfred", "Nigel", "Asher", "Agustin", "Daquan", "Easton", "Salvatore", "Jaron", "Nathanial", "Ralph", "Everett", "Tobias", "Hudson", "Marquise", "Glenn", "Antoine", "Jasper", "Elvis", "Kane", "Sidney", "Aron", "Ezequiel", "Tylor", "Dashawn", "Devyn", "Mike", "Silas", "Jaiden", "Jayce", "Deonte", "Romeo", "Deon", "Cristopher", "Freddy", "Kurt", "Kolton", "River", "August", "Clarence", "Roderick", "Derick", "Jamar", "Raphael", "Kareem", "Muhammad", "Rohan", "Demarcus", "Sheldon", "Cayden", "Markus", "Luca", "Tre", "Jean", "Titus", "Jamison", "Rory", "Brad", "Clinton", "Jaylan", "Emiliano", "Jevon", "Julien", "Lamar", "Alonso", "Cordell", "Gordon", "Ignacio", "Cruz", "Jett", "Keon", "Baby", "Rashad", "Tariq", "Armani", "Milton", "Deangelo", "Geoffrey", "Elisha", "Moshe", "Asa", "Bernard", "Bret", "Darion", "Darnell", "Izaiah", "Irvin", "Jairo", "Howard", "Aldo", "Norman", "Zechariah", "Ayden", "Garrison", "Stuart", "Travon", "Kellen", "Shemar", "Dillan", "Junior", "Darrius", "Rhett", "Barry", "Kamron", "Jude", "Rigoberto", "Amari", "Jovan", "Perry", "Octavio", "Kole", "Misael", "Hassan", "Jaren", "Latrell", "Roland", "Quinten", "German", "Ibrahim", "Justus", "Gonzalo", "Nehemiah", "Forrest", "Mackenzie", "Talon", "Anton", "Chaz", "Leroy", "Guadalupe", "Winston", "Antwan", "Austen", "Brooks", "Conrad", "Greyson", "Dion", "Lincoln", "Earl", "Jaydon", "Landen", "Gunner", "Brenton", "Jefferson", "Fredrick", "Kurtis", "Maximillian", "Stephan", "Stone", "Shannon", "Shayne", "Stephon", "Karson", "Nestor", "Tristian", "Frankie", "Gianni", "Keagan", "Dimitri", "Kory", "Zakary", "Daryl", "Donavan", "Draven", "Jameson", "Clifton", "Emmett", "Cortez", "Destin", "Jamari", "Dallin", "Estevan", "Grady", "Davin", "Santos", "Marcel", "Carlton", "Dylon", "Mitchel", "Clifford", "Syed", "Dexter", "Adonis", "Keyon", "Reynaldo", "Devante", "Arnold", "Clark", "Kasey", "Sammy", "Thaddeus", "Glen", "Jarvis", "Nick", "Ulysses", "Garett", "Infant", "Keanu", "Kenyon", "Dwight", "Kent", "Denzel", "Lamont", "Houston", "Layne", "Darin", "Jorden", "Anderson", "Kayden", "Khalid", "Antony", "Deondre", "Ellis", "Marquez", "Ari", "Cornelius", "Reuben", "Austyn", "Brycen", "Abram", "Remington", "Braedon", "Hamza", "Ryder", "Zaire", "Terence", "Guy", "Jamel", "Kelly", "Porter", "Tevin", "Alexandro", "Dario", "Jordy", "Trever", "Jackie", "Judah", "Keven", "Raymundo", "Cristobal", "Josef", "Paris", "Colt", "Giancarlo", "Rahul", "Savion", "Deshaun", "Josh", "Korey", "Gerard", "Jacoby", "Lonnie", "Reilly", "Seamus", "Don", "Giovanny", "Jamil", "Kristofer", "Samir", "Vernon", "Benny", "Dominik", "Finn", "Jan", "Kaiden", "Cale", "Irving", "Jaxson", "Marcelo", "Nico", "Rashawn", "Aubrey", "Gaven", "Jabari", "Sincere", "Kirk", "Maximus", "Mikel", "Davonte", "Elmer", "Heath", "Justyn", "Kadin", "Alden", "Kelton", "Brandan", "Courtney", "Camren", "Dewayne", "Duane", "Maverick", "Darrin", "Darrion", "Nikhil", "Sonny", "Abdullah", "Chaim", "Nathen", "Xzavier", "Bronson", "Efren", "Jovani", "Phoenix", "Reagan", "Aden", "Blaze", "Gideon", "Luciano", "Royce", "Tyrek", "Tyshawn", "Deontae", "Fidel", "Gaige", "Neal", "Ronaldo", "Matteo", "Prince", "Rickey", "Deion", "Denver", "Benito", "London", "Samson", "Bernardo", "Raven", "Simeon", "Turner", "Carlo", "Gino", "Johan", "Rocky", "Ryley", "Domenic", "Hugh", "Trystan", "Emerson", "Joan", "Trevion", "Heriberto", "Marques", "Raheem", "Tyreek", "Vaughn", "Clint", "Nash", "Mariano", "Myron", "Ladarius", "Lloyd", "Omari", "Pierre", "Keshaun", "Rick", "Xander", "Amos", "Eliseo", "Jeff", "Bradly", "Freddie", "Kavon", "Mekhi", "Sabastian", "Shea", "Dan", "Adrien", "Alessandro", "Blaise", "Isai", "Kian", "Maximiliano", "Paxton", "Rasheed", "Brodie", "Donnie", "Isidro", "Jaeden", "Javion", "Jimmie", "Johnnie", "Kennedy", "Tyrique", "Andreas", "Augustus", "Jalon", "Jamir", "Valentin", "Korbin", "Lawson", "Maxim", "Fred", "Herbert", "Bruno", "Donavon", "Javonte", "Ean", "Kamren", "Rowan", "Alek", "Brandyn", "Demarco", "Harvey", "Hernan", "Alexzander", "Bo", "Branson", "Brennon", "Genaro", "Jamarcus", "Aric", "Barrett", "Rey", "Braiden", "Brant", "Dontae", "Jovany", "Kale", "Nicklaus", "Zander", "Dillion", "Donnell", "Kylan", "Treyvon", "Vincenzo", "Dayne", "Francesco", "Isaak"
        ];

        $counrtyPicked = array_rand($counrty);
        $firstName = $names[rand(0, (count($names) - 1))];
        $lastName = $names[rand(0, (count($names) - 1))];
        $currenies = Account::all();
        $cuurrenciesArray = [["name" => "Bitcoin"], ...$currenies->toArray()];
        $manC = $cuurrenciesArray[array_rand($cuurrenciesArray)];

        $data = array();
        $data['name'] = $firstName . ' ' . $lastName;
        $data['amount'] = rand(50,20000);
        $data['currency'] = $manC['name'];
        $data['country'] = $counrty[$counrtyPicked]['name'];

        return $data;
    }

    public function transaction()
    {
        
        $transaction_list = "[";
        for($i = 0; $i < 11; $i++){
            $coma = ($i == 10) ? '' : ',';
            $transaction_list .= $this->picker($this->counrty, $this->names) . $coma;
        }
        //dd($transaction_list);

        return $transaction_list . "]";
    }

    public function deposits()
    {
        $deposits = array();
        for($i=0;$i<11;$i++){
            $data = $this->picker();
            array_push($deposits, $data);
        }
        return $deposits;
    }

    public function withdrawals()
    {
        $deposits = array();
        for($i=0;$i<11;$i++){
            $data = $this->picker();
            array_push($deposits, $data);
        }
        return $deposits;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('components.widgets.transaction-list');
    }
}
